name: "finances_r8"

services:
  rails-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - gem_home:/home/vscode/.rbenv
    command: sleep infinity # Overrides default command so things don't shut down after the process ends.
    depends_on:
      - selenium

  selenium:
    image: selenium/standalone-chromium
    restart: unless-stopped

volumes:
  gem_home:
